version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - "/src/*"
      - "/tests/*"
      - "/tools/*"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 5
    groups:
      dotnet-dependencies:
        patterns:
          - "*"
