-- Especialidades médicas reconhecidas pela Resolução CFM nº 2.380/2024.
-- O catálogo é persistido no banco para continuar sendo a fonte de verdade do fluxo DB-First.

INSERT INTO `specialties` (
    `name`,
    `normalized_name`,
    `is_active`,
    `created_at_utc`,
    `updated_at_utc`,
    `row_version`
) VALUES
    ('Acupuntura', 'ACUPUNTURA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Alergia e imunologia', 'ALERGIA E IMUNOLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Anestesiologia', 'ANESTESIOLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Angiologia', 'ANGIOLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Cardiologia', 'CARDIOLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Cirurgia cardiovascular', 'CIRURGIA CARDIOVASCULAR', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Cirurgia da mão', 'CIRURGIA DA MAO', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Cirurgia de cabeça e pescoço', 'CIRURGIA DE CABECA E PESCOCO', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Cirurgia do aparelho digestivo', 'CIRURGIA DO APARELHO DIGESTIVO', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Cirurgia geral', 'CIRURGIA GERAL', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Cirurgia oncológica', 'CIRURGIA ONCOLOGICA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Cirurgia pediátrica', 'CIRURGIA PEDIATRICA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Cirurgia plástica', 'CIRURGIA PLASTICA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Cirurgia torácica', 'CIRURGIA TORACICA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Cirurgia vascular', 'CIRURGIA VASCULAR', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Clínica médica', 'CLINICA MEDICA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Coloproctologia', 'COLOPROCTOLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Dermatologia', 'DERMATOLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Endocrinologia e metabologia', 'ENDOCRINOLOGIA E METABOLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Endoscopia', 'ENDOSCOPIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Gastroenterologia', 'GASTROENTEROLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Genética médica', 'GENETICA MEDICA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Geriatria', 'GERIATRIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Ginecologia e obstetrícia', 'GINECOLOGIA E OBSTETRICIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Hematologia e hemoterapia', 'HEMATOLOGIA E HEMOTERAPIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Homeopatia', 'HOMEOPATIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Infectologia', 'INFECTOLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Mastologia', 'MASTOLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Medicina de emergência', 'MEDICINA DE EMERGENCIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Medicina de família e comunidade', 'MEDICINA DE FAMILIA E COMUNIDADE', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Medicina do trabalho', 'MEDICINA DO TRABALHO', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Medicina do tráfego', 'MEDICINA DO TRAFEGO', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Medicina esportiva', 'MEDICINA ESPORTIVA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Medicina física e reabilitação', 'MEDICINA FISICA E REABILITACAO', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Medicina intensiva', 'MEDICINA INTENSIVA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Medicina legal e perícia médica', 'MEDICINA LEGAL E PERICIA MEDICA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Medicina nuclear', 'MEDICINA NUCLEAR', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Medicina preventiva e social', 'MEDICINA PREVENTIVA E SOCIAL', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Nefrologia', 'NEFROLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Neurocirurgia', 'NEUROCIRURGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Neurologia', 'NEUROLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Nutrologia', 'NUTROLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Oftalmologia', 'OFTALMOLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Oncologia clínica', 'ONCOLOGIA CLINICA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Ortopedia e traumatologia', 'ORTOPEDIA E TRAUMATOLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Otorrinolaringologia', 'OTORRINOLARINGOLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Patologia', 'PATOLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Patologia clínica/medicina laboratorial', 'PATOLOGIA CLINICA/MEDICINA LABORATORIAL', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Pediatria', 'PEDIATRIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Pneumologia', 'PNEUMOLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Psiquiatria', 'PSIQUIATRIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Radiologia e diagnóstico por imagem', 'RADIOLOGIA E DIAGNOSTICO POR IMAGEM', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Radioterapia', 'RADIOTERAPIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Reumatologia', 'REUMATOLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1),
    ('Urologia', 'UROLOGIA', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 1)
ON DUPLICATE KEY UPDATE
    `name` = VALUES(`name`),
    `is_active` = 1,
    `updated_at_utc` = UTC_TIMESTAMP(6),
    `row_version` = `row_version` + 1;
