<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>7e2f9b86-4382-47f7-a66e-8be657d53413</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ViverApp.Security/ViverApp.Security.csproj" />
  </ItemGroup>

</Project>
